services:
  backend:
    container_name: back
    build: ./backend
    image: spring:dev
    volumes:
      - back-dir:/app
    networks:
      - moheng-network
    ports:
      - 80:8080
    expose:
      - 8080
    restart: always

volumes:
  back-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/backend"

networks:
  moheng-network:
    driver: bridge
