services:
  nginx:
    container_name: nginx
    image: nginx:dev
    build: ./nginx
    networks:
      - moheng-network
    ports:
      - "80:80"
    restart: always

  backend:
    container_name: back
    image: spring:dev
    build: ./backend
    volumes:
      - back-dir:/app
    networks:
      - moheng-network
    ports:
      - 8080:8080
    restart: always
    environment:
      - LOGGING_LEVEL_ROOT=ERROR

  frontend:
    container_name: front
    image: react:dev
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    volumes:
      - front-dir:/usr/app
    networks:
      - moheng-network
    ports: # CORS 3000 allowed
      - 3000:5173 # host:container
    restart: always
    environment:
      - NODE_ENV=development

  ai:
    container_name: ai
    image: fastapi:dev
    build: ./ai
    volumes:
      - ai-dir:/app
    networks:
      - moheng-network
    ports:
      - 8000:8000
    restart: always

volumes:
  back-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend
  front-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./frontend
  ai-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./ai

networks:
  moheng-network:
    driver: bridge
