services:
  nginx:
    container_name: nginx
    image: nginx:prod
    build:
      context: .
      dockerfile: Dockerfile.nginx
    networks:
      - moheng-network
    ports:
      - "80:80"
    restart: always

  backend:
    container_name: back
    image: spring:prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    networks:
      - moheng-network
    expose:
      - "8080"
    restart: always
    environment:
      - LOGGING_LEVEL_ROOT=ERROR

  ai:
    container_name: ai
    image: fastapi:prod
    build: ./ai
    networks:
      - moheng-network
    expose:
      - "8000"
    restart: always

networks:
  moheng-network:
    driver: bridge
