[tool.poetry]
name = "moheng"
version = "0.1.0"
description = ""
authors = ["Do-yoon <1.kim.doyoon@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

