version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: 도움말
    cmd: task --list-all
    silent: true

  front:
    desc: 프론트 UI 개발 서버 실행
    cmd: docker compose -f compose.frontend.yaml up --build

  dev:
    preconditions:
      - test -f compose.dev.yaml
    desc: 통합 개발 환경 실행
    cmd: docker compose -f compose.dev.yaml up --build

  prod:
    desc: 프로덕션 환경 실행
    cmd: docker compose -f compose.prod.yaml up --build

  up:
    desc: 컨테이너 실행
    cmd: docker compose up --build

  down:
    desc: 컨테이너 중지
    cmd: docker compose down

  clean:
    desc: 컨테이너 삭제, 네트워크 삭제, 볼륨 삭제, 이미지 삭제, 빌드 캐시 삭제
    cmd: docker system prune -a
