name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    # if: ${{ contains(github.event.*.labels.*.name, 'gpt review') }} # Optional; to run only when a label is attached
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ChatGPT Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-3.5-turbo # https://platform.openai.com/docs/models
          PROMPT: >
            Please perform a comprehensive code review on the following code diff. Specifically, focus on:
            1. Correctness: Are there any logical errors or bugs in the code?
            2. Code Style: Does the code follow best practices and coding standards? Are there any style issues?
            3. Performance: Are there any potential performance bottlenecks or inefficiencies?
            4. Security: Are there any security vulnerabilities or potential risks in the code?
            5. Readability: Is the code easy to read and understand? Are there any comments or documentation that could be improved?
            6. Maintainability: Is the code modular and maintainable? Are there any refactoring suggestions?
          top_p: 1 # https://platform.openai.com/docs/api-reference/chat/create#chat/create-top_p
          temperature: 0.7 # https://platform.openai.com/docs/api-reference/chat/create#chat/create-temperature
          max_tokens: 4096 # gpt-3.5-turbo model's maximum token count
          MAX_PATCH_LENGTH: 10000 # if the patch/diff length is larger than MAX_PATCH_LENGTH, it will be ignored and won't review. By default, with no MAX_PATCH_LENGTH set, there is also no limit for the patch/diff length.
